### ISSUE TITLE
Flash example

### ISSUE THREAD

**Issue by brahmafear** [stelgenhof/AiLight#1]
Thanks for your work on this.  Have been testing on two bulbs for a few days now (with HomeAssistant).  All working except I can't seem to get flash config working.  Do you have an example config for this that I can test?

Thanks.

**Comment by stelgenhof** [comment]
Ah, yes. Flashing is definitely possible however I admit not part of the instructions yet. Let me add that as soon as possible.

**Comment by stelgenhof** [comment]
Created a wiki page how you can use the Flash feature: [Flashing the Light](https://github.com/stelgenhof/AiLight/wiki/Flashing-the-Light)
