### ISSUE TITLE
Undefined Variable Errors Save Function

### ISSUE THREAD

**Issue by delian7** [stelgenhof/AiLight#10]
Tried making a PR, but don't have permission. 

In line 449 in app.js, `var s` should be initialized as an empty object `var s ={}, msg = {};`. Otherwise an error ensues preventing saving any user settings. 

![undefined-bug](https://user-images.githubusercontent.com/4530694/27005946-c5ed6ed8-4ddd-11e7-8c1d-c80cd7cdb8d1.png)

**Comment by stelgenhof** [comment]
Thanks for catching this! I can confirm I also get this error message. Perhaps my JavaScript knowledge is getting rusty; I thought `var s, msg = {};` would initialize both variables. :( 

Already checked that your suggestions works. I'll change it asap.

As for the PR, did you create a fork and from there created a PR?

**Comment by delian7** [comment]
Ahh I didn't fork: I tried cloning the repo in sourcetree, made a branch, and tried to push that branch to do a PR. That makes sense.
