### ISSUE TITLE
Domoticz support in the future?

### ISSUE THREAD

**Issue by duelago** [stelgenhof/AiLight#15]
I really like this project. I'm up and running and everything works as advertised. 
I'm new to MQTT and my backend is Domoticz. Any plans to support Domoticz in a future release?

I really don't have the skills to implement this support myself.

Keep up the good work :)

 /David

**Comment by stelgenhof** [comment]
Thanks for the kind words! Domoticz wasn't really on the radar but definitely can have a look into it.

**Comment by stelgenhof** [comment]
I took some time to check Domoticz out and the MQTT integration is pretty simple. I have now a sandbox Domoticz and tried to set up a light/switch but coming from Home Assistant, the entire setup feels a bit strange. 

I managed successfully to publish an MQTT payload to Domoticz, but had a hard time figuring out how to integrate with an RGBW light. 

Do you have any pointers how I can do that? Guess I need to play around a little bit more..

**Comment by duelago** [comment]
Nice to hear that you are on the case! I'm afraid I'm more a user than a developer, so I'm not sure how I can help you. Maybe you can get a hint by looking at the implementation of other lamps in Domoticz? I'm using MiLights and they work just fine, but they are not talking MQTT.

https://www.domoticz.com/wiki/Limitless/AppLamp_LED

**Comment by stelgenhof** [comment]
After fiddling around a bit more in Domoticz, I got it working. Meaning: I could send and receive commands via MQTT. The way Domoticz handles this, is quite different from what I'm used to. 

Let me see how this could be integrated in the AiLight firmware.
