### ISSUE TITLE
The REST API examples doesn't work

### ISSUE THREAD

**Issue by bofh69** [stelgenhof/AiLight#18]
With curl 7.47.0, the REST API examples with method PATCH  don't work. A Content-Type header is needed as well:
-H 'Content-Type: application/json'

**Comment by stelgenhof** [comment]
Thanks for catching this! Indeed the Content-Type header is required when using the PATCH method. I will update the example as soon as possible.

**Comment by stelgenhof** [comment]
Example updated!
