### ISSUE TITLE
homebridge plugin AiLight

### ISSUE THREAD

**Issue by ageorgios** [stelgenhof/AiLight#20]
Are there any plans for a homebridge plugin?

**Comment by stelgenhof** [comment]
Not sure what you mean by a 'Homebridge plugin', but you can use Homebridge together with Home Assistant using the homebridge-homeassistant plugin.

I have used sometime ago, and was perfectly able to use iOS' Siri to control my light :)

**Comment by badgerhome** [comment]
I use homeassistant-homebridge with AiLight MQTT bulbs, brightness and colours both work too!

**Comment by ageorgios** [comment]
in case you don't use homeassistant there are plugins for specific devices, like homebridge-aqara (for xiaomi devices) homebridge-yeelight (for xiaomi bulbs) etc.

**Comment by stelgenhof** [comment]
Ah, I see what you mean. Unfortunately I haven't really looked at that possibility yet :)

**Comment by stelgenhof** [comment]
@ageorgios Your wish has been granted! Created a homebridge plugin for the AiLight firmware. More details you can find here: https://www.npmjs.com/package/homebridge-ailight or here: https://github.com/stelgenhof/homebridge-ailight

**Comment by ageorgios** [comment]
you rock!

**Comment by stelgenhof** [comment]
Closing this issue as a dedicated Homebridge plugin is now available here: https://github.com/stelgenhof/homebridge-ailight
