### ISSUE TITLE
Working with Expower 7W Smart WiFi Blub's

### ISSUE THREAD

**Issue by dawsmac** [stelgenhof/AiLight#22]
Hi Stelgenhof cheers for this... in the UK I have four Expower 7W Smart WiFi Blub that I got off Amazon and they are working with HA now because of your firmware 👍 

Happy Days...

https://www.amazon.co.uk/gp/product/B075Q9NHF2/ref=oh_aui_detailpage_o00_s00?ie=UTF8&psc=1

**Comment by stelgenhof** [comment]
Thanks @dawsmac ! Happy to hear you like the AiLight firmware. Don't hesitate to create an issue if something isn't working or if you have any good ideas for improvement :)

**Comment by stelgenhof** [comment]
Just updated the Wiki page for compatible bulbs.

**Comment by stelgenhof** [comment]
Added to Wiki.
