### ISSUE TITLE
Unable to flash lightbulb

### ISSUE THREAD

**Issue by apieronlogic** [stelgenhof/AiLight#27]
Code builds with a successful message, but getting this error when I try to upload:

> 
> before_build([".pioenvs\dev\src\main.ino.o"], ["src\main.ino.cpp"])
> C:\Users\Philip\Documents\AILight\AiLight-master/node_modules/.bin/gulp
> The system cannot find the path specified.
> *** Error 1
> Compiling .pioenvs\dev\src\main.ino.o
> Linking .pioenvs\dev\firmware.elf
> Checking program size
> text       data     bss     dec     hex filenameE
> rror: The program size (438723 bytes) is greater than maximum allowed (434160 bytes)4
> 28655     10068   32168  470891   72f6b .pioenvs\dev\firmware.elf*
> ** [.pioenvs\dev\firmware.elf] Explicit exit, status 1

Thanks for the help!

**Comment by stelgenhof** [comment]
In case you are compiling the firmware yourself and want to make changes the Web UI, you need to make sure you have Gulp and NodeJS installed (I am aware the documentation needs some updating)

However, if not, you can safely ignore the first error.

Can you tell me what light bulb you are using for uploading? Not sure why you get this message that the size is exceeding the maximum. Just wondering what your settings are and what chip your light bulb is using.

**Comment by apieronlogic** [comment]
Thanks for your quick reply! Maybe I'll get around to some of the more advanced features later, but just learning the basics for now.

This is what I ordered: https://www.amazon.com/gp/product/B01H4ZW7I6/ref=oh_aui_detailpage_o03_s00?ie=UTF8&psc=1

I was able to install Espuna and got this information from it: 
![capture](https://user-images.githubusercontent.com/30306008/34970377-544a04f2-fa31-11e7-8424-78256435ea6d.PNG)

Maybe this one isn't compatible? Is there another device you would recommend using?

**Comment by stelgenhof** [comment]
Can't yet tell if it is compatible or not. From the product description, it seems to be a proper ESP8266 based light bulb. 

However some manufacturers use different LED driver chips. This firmware is certain to work with lightbulbs that have the MY9291 LED driver. See also this wiki Page:  https://github.com/stelgenhof/AiLight/wiki/Compatible-Light-Bulbs

You can verify your LED driver by checking the chips on the PCB board.  

Your ESPURNA screenshot tells me you have configured the ESPURNA firmware as a D1 Relay Shield. Sure that is correct? You might want to recompile Espurna with the correct configuration (as a smart LED light instead).

**Comment by apieronlogic** [comment]
Thank you so much! I'll take a look at those other products. 

You were right about the ESPURNA screenshot. I was able to get that up and running.

**Comment by gmschade** [comment]
Just had same problem. solved it by:
1. build dev
2. go into folder .pioenvs/dev/
3. flash firmware.bin using esptool.py

**Comment by stelgenhof** [comment]
@apieronlogic Quick follow up on your issue: It seems that the Arduino ESP8266 v2.4.0 framework has some issues. People have been reporting that their code increased in size significantly. 

I've already tested reverting back to 2.3.0 and that works fine. I'll make some changes so the firmware stays with 2.3.0 (for the moment).

**Comment by stelgenhof** [comment]
@apieronlogic I believe I found the culprit. The new master branch has a few updates and I can confirm it works with Arduino ESP8266 v2.4.0 framework.

**Comment by stelgenhof** [comment]
Included in the just released version 0.6.0.
