### ISSUE TITLE
Errors during compile 'WIFI_SSID' was not declared in this scope

### ISSUE THREAD

**Issue by rust84** [stelgenhof/AiLight#32]
Encountering an error when trying to compile. Configured the default values for wifi and mqtt in src/config.h. The compiler is complaining about variables not being declared.

I noticed that if I comment out the wifi configuration (default) then the build finishes ok. 

Am using platformio installed with pip. Tested on Windows and Linux and it is the same. See my config below.

`******************************************************************************************************************************************************
If you like PlatformIO, please:
- follow us on Twitter to stay up-to-date on the latest project news > https://twitter.com/PlatformIO_Org
- star it on GitHub > https://github.com/platformio/platformio
- try PlatformIO IDE for IoT development > http://platformio.org/platformio-ide
- support us with PlatformIO Plus > https://pioplus.com
******************************************************************************************************************************************************

[Wed Mar  7 13:20:34 2018] Processing dev (extra_scripts: build.py; build_flags: -DDEBUG -g -Wall -Wl,-Tesp8266.flash.1m128.ld; lib_deps: ArduinoJson, AsyncMqttClient, xoseperez/my9291, ESPAsyncTCP, ESP Async WebServer; platform: espressif8266; board: esp8285; framework: arduino)
------------------------------------------------------------------------------------------------------------------------------------------------------
LibraryManager: Installing id=64
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
LibraryManager: Installing id=346
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
LibraryManager: Installing id=305 @ ^1.1.0
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
LibraryManager: Installing id=1826 @ ^1.0.0
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
LibraryManager: Installing my9291
git version 2.7.4
Cloning into '/home/russell/repos/AiLight/.piolibdeps/_tmp_installing-69RTfQ-package'...
remote: Counting objects: 20, done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 20 (delta 0), reused 10 (delta 0), pack-reused 0
Unpacking objects: 100% (20/20), done.
Checking connectivity... done.
LibraryManager: Installing id=306
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
PlatformManager: Installing espressif8266
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
espressif8266 @ 1.6.0 has been successfully installed!
The platform 'espressif8266' has been successfully installed!
The rest of packages will be installed automatically depending on your build environment.
PackageManager: Installing toolchain-xtensa @ ~1.40802.0
Downloading  [####################################]  100%          
Unpacking  [####################################]  100%          
PackageManager: Installing tool-esptool @ ~1.409.0
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
PackageManager: Installing framework-arduinoespressif8266 @ ~1.20400.0
Downloading  [####################################]  100%          
Unpacking  [####################################]  100%          
CorePackageManager: Installing tool-scons @ ~3.20501.2
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
tool-scons @ 3.20501.2 has been successfully installed!
Verbose mode can be enabled via `-v, --verbose` option
Converting main.ino
Collected 32 compatible libraries
Scanning dependencies...
Library Dependency Graph ( http://bit.ly/configure-pio-ldf )
|-- <ArduinoJson> v5.13.1
|-- <AsyncMqttClient> v0.8.2
|   |-- <ESPAsyncTCP> v1.1.3
|   |   |-- <ESP8266WiFi> v1.0
|-- <my9291> v2.0.0 #fd9271c
|-- <ESPAsyncTCP> v1.1.3
|   |-- <ESP8266WiFi> v1.0
|-- <ESP Async WebServer> v1.1.1
|   |-- <ESPAsyncTCP> v1.1.3
|   |   |-- <ESP8266WiFi> v1.0
|   |-- <Hash> v1.0
|   |-- <ESP8266WiFi> v1.0
|   |-- <ArduinoJson> v5.13.1
|-- <AiLight>
|   |-- <my9291> v2.0.0 #fd9271c
|-- <EEPROM> v1.0
|-- <ArduinoOTA> v1.0
|   |-- <ESP8266WiFi> v1.0
|   |-- <ESP8266mDNS>
|   |   |-- <ESP8266WiFi> v1.0
|-- <ESP8266mDNS>
|   |-- <ESP8266WiFi> v1.0
|-- <Hash> v1.0
|-- <ESP8266WiFi> v1.0
|-- <Ticker> v1.0
Compiling .pioenvs/dev/src/main.ino.cpp.o
Archiving .pioenvs/dev/libFrameworkArduinoVariant.a
Indexing .pioenvs/dev/libFrameworkArduinoVariant.a
Compiling .pioenvs/dev/FrameworkArduino/Esp.cpp.o
Compiling .pioenvs/dev/FrameworkArduino/FS.cpp.o
Compiling .pioenvs/dev/FrameworkArduino/FunctionalInterrupt.cpp.o
Compiling .pioenvs/dev/FrameworkArduino/HardwareSerial.cpp.o
Compiling .pioenvs/dev/FrameworkArduino/IPAddress.cpp.o
Compiling .pioenvs/dev/FrameworkArduino/MD5Builder.cpp.o
Compiling .pioenvs/dev/FrameworkArduino/Print.cpp.o
Compiling .pioenvs/dev/FrameworkArduino/Schedule.cpp.o
In file included from src/main.h:20:0,
from /home/russell/repos/AiLight/src/main.ino:13:
src/config.h:43:1: error: 'define' does not name a type
define WIFI_SSID "Asgard2"
^
In file included from lib/AiLight/AiLight.hpp:19:0,
from src/main.h:35,
from /home/russell/repos/AiLight/src/main.ino:13:
.piolibdeps/my9291/src/my9291.h:41:3: error: 'my9291_cmd_one_shot_t' does not name a type
} my9291_cmd_one_shot_t;
^
.piolibdeps/my9291/src/my9291.h:72:9: error: 'my9291_cmd_one_shot_t' does not name a type
my9291_cmd_one_shot_t one_shot:1;
^
Compiling .pioenvs/dev/FrameworkArduino/Stream.cpp.o
Compiling .pioenvs/dev/FrameworkArduino/StreamString.cpp.o
Compiling .pioenvs/dev/FrameworkArduino/Tone.cpp.o
Compiling .pioenvs/dev/FrameworkArduino/Updater.cpp.o
/home/russell/repos/AiLight/src/main.ino: In function 'void loadFactoryDefaults()':
/home/russell/repos/AiLight/src/main.ino:57:19: error: 'MQTT_PORT' was not declared in this scope
cfg.mqtt_port = MQTT_PORT;
^
/home/russell/repos/AiLight/src/main.ino:58:30: error: 'MQTT_SERVER' was not declared in this scope
os_strcpy(cfg.mqtt_server, MQTT_SERVER);
^
/home/russell/repos/AiLight/src/main.ino:76:28: error: 'WIFI_SSID' was not declared in this scope
os_strcpy(cfg.wifi_ssid, WIFI_SSID);
^
/home/russell/repos/AiLight/src/main.ino:77:27: error: 'WIFI_PSK' was not declared in this scope
os_strcpy(cfg.wifi_psk, WIFI_PSK);
^
Compiling .pioenvs/dev/FrameworkArduino/WMath.cpp.o
/home/russell/repos/AiLight/src/_web.ino: In function 'void wsProcessMessage(uint8_t, char*, size_t)':
/home/russell/repos/AiLight/src/_web.ino:188:34: error: 'MQTT_PORT' was not declared in this scope
: MQTT_PORT;
^
Compiling .pioenvs/dev/FrameworkArduino/WString.cpp.o
Compiling .pioenvs/dev/FrameworkArduino/abi.cpp.o
Compiling .pioenvs/dev/FrameworkArduino/base64.cpp.o
*** [.pioenvs/dev/src/main.ino.cpp.o] Error 1
============================================================= [ERROR] Took 33.12 seconds =============================================================

===================================================================== [SUMMARY] =====================================================================
Environment dev     	[ERROR]
Environment dev-ota 	[SKIP]
Environment prod    	[SKIP]
Environment prod-ota	[SKIP]
============================================================= [ERROR] Took 33.12 seconds =============================================================`

`/**
 * Ai-Thinker RGBW Light Firmware - Configuration
 *
 * This file is part of the Ai-Thinker RGBW Light Firmware.
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.

 * Created by Sacha Telgenhof <stelgenhof at gmail dot com>
 * (https://www.sachatelgenhof.nl)
 * Copyright (c) 2016 - 2018 Sacha Telgenhof
 */

/**
 * Light
 * ---------------------------
 * Use the below variables to set the default behaviour of your Ai-Thinker RGBW
 * Light. These will be used as the factory defaults of your device.
 */
#define LIGHT_STATE false
#define LIGHT_BRIGHTNESS 0
#define LIGHT_COLOR_TEMPERATURE 0
#define LIGHT_COLOR_RED 64
#define LIGHT_COLOR_GREEN 64
#define LIGHT_COLOR_BLUE 64
#define LIGHT_COLOR_WHITE 0

#define HOSTNAME "AiLight"
#define ADMIN_PASSWORD "hinotori"

/**
 * OTA (Over The Air) Updates
 * ---------------------------
 */
#define OTA_PORT 8266

/**
 * WiFi
 * ---------------------------
 * Use the below variables to set the default WiFi settings of your Ai-Thinker
 * RGBW Light. These will be used as the factory defaults of your device. If no
 * SSID/PSK are provided, your Ai-Thinker RGBW light will start in AP mode.
 */
define WIFI_SSID "Asgard2"
define WIFI_PSK "secret"
#define WIFI_OUTPUT_POWER 1.0 // 20.5 is the maximum output power

/**
 * MQTT
 * ---------------------------
 * Use the below variables to set the default MQTT settings of your Ai-Thinker
 * RGBW Light. These will be used as the factory defaults of your device and
 * making the connection to your Home Assistant instance. Most of these settings
 * can also be changed in the UI environment.
 */
define MQTT_PORT 1883
define MQTT_SERVER "192.168.1.81"
#define MQTT_USER ""
#define MQTT_PASSWORD ""
#define MQTT_RECONNECT_TIME 10000
#define MQTT_QOS_LEVEL 0
#define MQTT_RETAIN false
#define MQTT_KEEPALIVE 30

#define MQTT_PAYLOAD_ON "ON"
#define MQTT_PAYLOAD_OFF "OFF"

#define MQTT_STATUS_ONLINE "online"
#define MQTT_STATUS_OFFLINE "offline"

#define MQTT_HOMEASSISTANT_DISCOVERY_ENABLED false
#define MQTT_HOMEASSISTANT_DISCOVERY_PREFIX "homeassistant"

/**
 * HTTP
 * ---------------------------
 * Use the below variables to set the default HTTP settings of your Ai-Thinker
 * RGBW Light. These will be used as the factory defaults of your device.
 */
#define REST_API_ENABLED false`
Build i

`******************************************************************************************************************************************************
If you like PlatformIO, please:
- follow us on Twitter to stay up-to-date on the latest project news > https://twitter.com/PlatformIO_Org
- star it on GitHub > https://github.com/platformio/platformio
- try PlatformIO IDE for IoT development > http://platformio.org/platformio-ide
- support us with PlatformIO Plus > https://pioplus.com
******************************************************************************************************************************************************

[Wed Mar  7 13:20:34 2018] Processing dev (extra_scripts: build.py; build_flags: -DDEBUG -g -Wall -Wl,-Tesp8266.flash.1m128.ld; lib_deps: ArduinoJson, AsyncMqttClient, xoseperez/my9291, ESPAsyncTCP, ESP Async WebServer; platform: espressif8266; board: esp8285; framework: arduino)
------------------------------------------------------------------------------------------------------------------------------------------------------
LibraryManager: Installing id=64
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
LibraryManager: Installing id=346
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
LibraryManager: Installing id=305 @ ^1.1.0
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
LibraryManager: Installing id=1826 @ ^1.0.0
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
LibraryManager: Installing my9291
git version 2.7.4
Cloning into '/home/russell/repos/AiLight/.piolibdeps/_tmp_installing-69RTfQ-package'...
remote: Counting objects: 20, done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 20 (delta 0), reused 10 (delta 0), pack-reused 0
Unpacking objects: 100% (20/20), done.
Checking connectivity... done.
LibraryManager: Installing id=306
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
PlatformManager: Installing espressif8266
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
espressif8266 @ 1.6.0 has been successfully installed!
The platform 'espressif8266' has been successfully installed!
The rest of packages will be installed automatically depending on your build environment.
PackageManager: Installing toolchain-xtensa @ ~1.40802.0
Downloading  [####################################]  100%          
Unpacking  [####################################]  100%          
PackageManager: Installing tool-esptool @ ~1.409.0
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
PackageManager: Installing framework-arduinoespressif8266 @ ~1.20400.0
Downloading  [####################################]  100%          
Unpacking  [####################################]  100%          
CorePackageManager: Installing tool-scons @ ~3.20501.2
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
tool-scons @ 3.20501.2 has been successfully installed!
Verbose mode can be enabled via `-v, --verbose` option
Converting main.ino
Collected 32 compatible libraries
Scanning dependencies...
Library Dependency Graph ( http://bit.ly/configure-pio-ldf )
|-- <ArduinoJson> v5.13.1
|-- <AsyncMqttClient> v0.8.2
|   |-- <ESPAsyncTCP> v1.1.3
|   |   |-- <ESP8266WiFi> v1.0
|-- <my9291> v2.0.0 #fd9271c
|-- <ESPAsyncTCP> v1.1.3
|   |-- <ESP8266WiFi> v1.0
|-- <ESP Async WebServer> v1.1.1
|   |-- <ESPAsyncTCP> v1.1.3
|   |   |-- <ESP8266WiFi> v1.0
|   |-- <Hash> v1.0
|   |-- <ESP8266WiFi> v1.0
|   |-- <ArduinoJson> v5.13.1
|-- <AiLight>
|   |-- <my9291> v2.0.0 #fd9271c
|-- <EEPROM> v1.0
|-- <ArduinoOTA> v1.0
|   |-- <ESP8266WiFi> v1.0
|   |-- <ESP8266mDNS>
|   |   |-- <ESP8266WiFi> v1.0
|-- <ESP8266mDNS>
|   |-- <ESP8266WiFi> v1.0
|-- <Hash> v1.0
|-- <ESP8266WiFi> v1.0
|-- <Ticker> v1.0
Compiling .pioenvs/dev/src/main.ino.cpp.o
Archiving .pioenvs/dev/libFrameworkArduinoVariant.a
Indexing .pioenvs/dev/libFrameworkArduinoVariant.a
Compiling .pioenvs/dev/FrameworkArduino/Esp.cpp.o
Compiling .pioenvs/dev/FrameworkArduino/FS.cpp.o
Compiling .pioenvs/dev/FrameworkArduino/FunctionalInterrupt.cpp.o
Compiling .pioenvs/dev/FrameworkArduino/HardwareSerial.cpp.o
Compiling .pioenvs/dev/FrameworkArduino/IPAddress.cpp.o
Compiling .pioenvs/dev/FrameworkArduino/MD5Builder.cpp.o
Compiling .pioenvs/dev/FrameworkArduino/Print.cpp.o
Compiling .pioenvs/dev/FrameworkArduino/Schedule.cpp.o
In file included from src/main.h:20:0,
from /home/russell/repos/AiLight/src/main.ino:13:
src/config.h:43:1: error: 'define' does not name a type
define WIFI_SSID "Asgard2"
^
In file included from lib/AiLight/AiLight.hpp:19:0,
from src/main.h:35,
from /home/russell/repos/AiLight/src/main.ino:13:
.piolibdeps/my9291/src/my9291.h:41:3: error: 'my9291_cmd_one_shot_t' does not name a type
} my9291_cmd_one_shot_t;
^
.piolibdeps/my9291/src/my9291.h:72:9: error: 'my9291_cmd_one_shot_t' does not name a type
my9291_cmd_one_shot_t one_shot:1;
^
Compiling .pioenvs/dev/FrameworkArduino/Stream.cpp.o
Compiling .pioenvs/dev/FrameworkArduino/StreamString.cpp.o
Compiling .pioenvs/dev/FrameworkArduino/Tone.cpp.o
Compiling .pioenvs/dev/FrameworkArduino/Updater.cpp.o
/home/russell/repos/AiLight/src/main.ino: In function 'void loadFactoryDefaults()':
/home/russell/repos/AiLight/src/main.ino:57:19: error: 'MQTT_PORT' was not declared in this scope
cfg.mqtt_port = MQTT_PORT;
^
/home/russell/repos/AiLight/src/main.ino:58:30: error: 'MQTT_SERVER' was not declared in this scope
os_strcpy(cfg.mqtt_server, MQTT_SERVER);
^
/home/russell/repos/AiLight/src/main.ino:76:28: error: 'WIFI_SSID' was not declared in this scope
os_strcpy(cfg.wifi_ssid, WIFI_SSID);
^
/home/russell/repos/AiLight/src/main.ino:77:27: error: 'WIFI_PSK' was not declared in this scope
os_strcpy(cfg.wifi_psk, WIFI_PSK);
^
Compiling .pioenvs/dev/FrameworkArduino/WMath.cpp.o
/home/russell/repos/AiLight/src/_web.ino: In function 'void wsProcessMessage(uint8_t, char*, size_t)':
/home/russell/repos/AiLight/src/_web.ino:188:34: error: 'MQTT_PORT' was not declared in this scope
: MQTT_PORT;
^
Compiling .pioenvs/dev/FrameworkArduino/WString.cpp.o
Compiling .pioenvs/dev/FrameworkArduino/abi.cpp.o
Compiling .pioenvs/dev/FrameworkArduino/base64.cpp.o
*** [.pioenvs/dev/src/main.ino.cpp.o] Error 1
============================================================= [ERROR] Took 33.12 seconds =============================================================

===================================================================== [SUMMARY] =====================================================================
Environment dev     	[ERROR]
Environment dev-ota 	[SKIP]
Environment prod    	[SKIP]
Environment prod-ota	[SKIP]
============================================================= [ERROR] Took 33.12 seconds =============================================================`

`/**
 * Ai-Thinker RGBW Light Firmware - Configuration
 *
 * This file is part of the Ai-Thinker RGBW Light Firmware.
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.

 * Created by Sacha Telgenhof <stelgenhof at gmail dot com>
 * (https://www.sachatelgenhof.nl)
 * Copyright (c) 2016 - 2018 Sacha Telgenhof
 */

/**
 * Light
 * ---------------------------
 * Use the below variables to set the default behaviour of your Ai-Thinker RGBW
 * Light. These will be used as the factory defaults of your device.
 */
#define LIGHT_STATE false
#define LIGHT_BRIGHTNESS 0
#define LIGHT_COLOR_TEMPERATURE 0
#define LIGHT_COLOR_RED 64
#define LIGHT_COLOR_GREEN 64
#define LIGHT_COLOR_BLUE 64
#define LIGHT_COLOR_WHITE 0

#define HOSTNAME "AiLight"
#define ADMIN_PASSWORD "hinotori"

/**
 * OTA (Over The Air) Updates
 * ---------------------------
 */
#define OTA_PORT 8266

/**
 * WiFi
 * ---------------------------
 * Use the below variables to set the default WiFi settings of your Ai-Thinker
 * RGBW Light. These will be used as the factory defaults of your device. If no
 * SSID/PSK are provided, your Ai-Thinker RGBW light will start in AP mode.
 */
define WIFI_SSID "Asgard2"
define WIFI_PSK "secret"
#define WIFI_OUTPUT_POWER 1.0 // 20.5 is the maximum output power

/**
 * MQTT
 * ---------------------------
 * Use the below variables to set the default MQTT settings of your Ai-Thinker
 * RGBW Light. These will be used as the factory defaults of your device and
 * making the connection to your Home Assistant instance. Most of these settings
 * can also be changed in the UI environment.
 */
define MQTT_PORT 1883
define MQTT_SERVER "192.168.1.81"
#define MQTT_USER ""
#define MQTT_PASSWORD ""
#define MQTT_RECONNECT_TIME 10000
#define MQTT_QOS_LEVEL 0
#define MQTT_RETAIN false
#define MQTT_KEEPALIVE 30

#define MQTT_PAYLOAD_ON "ON"
#define MQTT_PAYLOAD_OFF "OFF"

#define MQTT_STATUS_ONLINE "online"
#define MQTT_STATUS_OFFLINE "offline"

#define MQTT_HOMEASSISTANT_DISCOVERY_ENABLED false
#define MQTT_HOMEASSISTANT_DISCOVERY_PREFIX "homeassistant"

/**
 * HTTP
 * ---------------------------
 * Use the below variables to set the default HTTP settings of your Ai-Thinker
 * RGBW Light. These will be used as the factory defaults of your device.
 */
#define REST_API_ENABLED false`

**Comment by stelgenhof** [comment]
I think you made a typ-o of some sorts when editing the config.h file. Most likely you didn't close a string (using quotes or double quotes) properly in the config.h file. If that occurs, then basically the syntax is garbled which could explain these errors.

Can you please check if your config.h file is correctly edited?

**Comment by rust84** [comment]
It was my fault for removing the # thinking it was already commented out. Been a long time since I did anything with c! Thanks for responding anyway.
