### ISSUE TITLE
Working bulbs

### ISSUE THREAD

**Issue by nickrout** [stelgenhof/AiLight#33]
I got mine here and they work perfectly https://www.alibaba.com/product-detail/High-Standard-Colorful-Smartphone-Remote-Control_60576662953.html?spm=a2700.7724838.0.0.jahydM

Perhaps add it to your page of working bulbs?

**Comment by stelgenhof** [comment]
Thanks! I've added it to the Wiki page :)

**Comment by moishap** [comment]
And here is another one : https://www.amazon.com/gp/product/B0769L9FNH/ref=oh_aui_detailpage_o00_s00?ie=UTF8&psc=1

**Comment by stelgenhof** [comment]
@moishap Thanks! Added it to the Wiki page.
