### ISSUE TITLE
Add Emwel Smart bulb to compatible list

### ISSUE THREAD

**Issue by SurfingSpider** [stelgenhof/AiLight#34]
I just wanted to let you know that the "[Emwel 7W Smart WiFi Bulb Light B22 Led Bulbs Works with Amazon Alexa Echo Remote Control by Smartphone IOS and Android 60W Equivalent [White, Energy Class A+]](http://amzn.eu/2HiYVXl)" bulb on amazon (which is currently on sale for £15) works with your firmware. Incase you wanted to add it to your compatible list.

**Comment by stelgenhof** [comment]
Thanks! Added it to the Wiki Page.
