### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by jonny190** [stelgenhof/AiLight#38]
Is there any planned support for:

https://www.banggood.com/ARILUX-AL-LC01-Super-Mini-LED-WIFI-Smart-RGB-Controller-For-RGB-LED-Strip-Light-DC-9-12V-p-1058603.html?rmmds=search&cur_warehouse=CN

LC01 | RGB | 5-28V | None | ~$8 
LC02 | RGBW | 9-12V | None | ~$11 
LC03 | RGB | 5-28V | IR | ~$12 
LC04 | RGBW | 9-12V | IR | ~$13
LC08 | RGBWW | 5-28V | None | ~$12 
LC09 | RGB | 5-28V | RF | ~$12 
LC10 | RGBW | 9-28V | RF | ~$14 
LC11 | RGBWW | 9-28V | RF | ~$15

**Comment by stelgenhof** [comment]
The AriLux LC0X controller series are not using a LED driver like the AiThinker Light bulb (and some other similar types). I am not planning any support for these as this firmware is only intended for AiThinker type light bulbs.
