### ISSUE TITLE
Question. Qube light bulb

### ISSUE THREAD

**Issue by jimpastos** [stelgenhof/AiLight#45]
I accidentally broke a Qube light bulb while moving some boxes and started to look into what I can salvage from its components.

Any chance AiLight can be used (or parts of it) to flash the bulb? The original is dead as Qube took down their servers. Would be good to have a project to revive them

From what i can tell it has an ESP8266EX and a bluetooth chipset. Not sure if it has any fancy LED controller or not

Im attaching some pics of the PCB. I can attach more if needed

![img_8405](https://user-images.githubusercontent.com/13491110/48309664-0ee60c00-e54d-11e8-9409-ecddb32016e6.jpeg)
![img_8406](https://user-images.githubusercontent.com/13491110/48309665-0ee60c00-e54d-11e8-9c6c-4b63d908ce10.jpeg)
![img_8407](https://user-images.githubusercontent.com/13491110/48309666-0ee60c00-e54d-11e8-9f5a-0689e507e884.jpeg)
![img_8410](https://user-images.githubusercontent.com/13491110/48309667-0ee60c00-e54d-11e8-87b2-b29a8d826a9e.jpeg)
![img_8411](https://user-images.githubusercontent.com/13491110/48309668-0ee60c00-e54d-11e8-9347-b55182fa9aaa.jpeg)
![img_8414](https://user-images.githubusercontent.com/13491110/48309723-d430a380-e54d-11e8-9237-dca07939bc54.jpeg)
![img_8413](https://user-images.githubusercontent.com/13491110/48309724-d430a380-e54d-11e8-94e7-a2c77e37ee05.jpeg)
![img_8412](https://user-images.githubusercontent.com/13491110/48309725-d4c93a00-e54d-11e8-9950-83869ce9ede6.jpeg)

**Comment by stelgenhof** [comment]
Thanks @jimpastos for the photos. Indeed it has both an ESP8266EX and a CSR1010 Bluetooth chip for communications. It would be interesting to see what kind of LED driver it is using. From the photos I couldn't see one. Unless the LEDs are controlled in a different manner.

**Comment by jimpastos** [comment]
I couldn’t see any specific driver. Seems it just controls them with N-channel Mosfets with a secondary board that connects to the LED pcb

**Comment by stelgenhof** [comment]
I see. The AiLight is currently designed to work with a LED driver only, not with the ESP8266 driving any MOSFET's. It would be possible, however not (yet) designed to do so. 

Cheers! Sacha

**Comment by jimpastos** [comment]
If I could figure out how to flash this with custom firmware, i can experiment with it. 
For now i can probably try to use the mosfet pcb and the led grid on a pi and attempt to drive with its GPIOs. 

Ideally running the ESP with wifi and bluetooth with something custom with be perfect

**Comment by stelgenhof** [comment]
I think the flashing isn't the hardest part. You would just need to connect wires to the ESP8266 chip directly.

**Comment by stelgenhof** [comment]
@jimpastos Just wanted to know if I can close this issue? Did you get around resolving your issues?

Cheers! Sacha

**Comment by jimpastos** [comment]
When I played around with it I measured that the circuit was using 20+ Volts so I didn’t bother trying drive it with other components. 
I guess someone with more time and dedication should play with this :)

You can close the ticket
