### ISSUE TITLE
MiLight 9W incompatible

### ISSUE THREAD

**Issue by virtualducttape** [stelgenhof/AiLight#46]
Just wanted to leave a note, the Mi-Light 9W bulb is NOT compatible. The exterior looks like the Sonoff B1, however it's using a STM 8S003F3P6 chip inside. I ordered it from Amazon (this bulb: https://www.amazon.com/gp/product/B077TGTLWQ/ref=oh_aui_detailpage_o03_s00?ie=UTF8&th=1 )

**Comment by stelgenhof** [comment]
Hi @virtualducttape 

Thanks for the information. I will add this to the list of incompatible lights.

Cheers! Sacha

**Comment by stelgenhof** [comment]
I've update the Wiki page with this information. Thanks!
