### ISSUE TITLE
Losing config after powering off

### ISSUE THREAD

**Issue by nospam2k** [stelgenhof/AiLight#48]
This doesn't happen every time but sometimes when I cycle power on the bulb, it goes back into the default AP state and I have to re-provision the bulb (connect to bulb AP, re-enter ssid, pw, etc). I have taken the .bin file from platformio and used "sudo esptool.py --port /dev/cu.usbserial -b 115200 write_flash 0x0 AiLight.bin" to flash it. Is there any reason not to do it this way?

**Comment by stelgenhof** [comment]
I have not experienced myself that the config is lost after powering off. There is one bulb in our house that everybody uses with the regular mains switch and going strong for almost two years.

What version of the firmware are you using? You can definitely flash that way. Don't you use OTA?

**Comment by nospam2k** [comment]
I'm having problems with trying the OTA. I get this error every time.

Sending invitation to 192.168.0.61
Authenticating...OK
01:19:47 [INFO]: Waiting for device...
Uploading: [============================================================] 100% Done...

01:20:02 [INFO]: Waiting for result...
01:20:02 [INFO]: Result: 488
01:20:02 [INFO]: Result: 1008OK
01:20:02 [INFO]: Result:
01:20:02 [INFO]: Result:
01:20:02 [INFO]: Result:
01:20:02 [ERROR]: Error response from device

I tried two different bulbs with the same result. This is the command line:

"/Users/test/.platformio/penv/bin/python" "/Users/test/.platformio/packages/tool-espotapy/espota.py" --debug --progress -i 192.168.0.61 --auth="xxxxxxx" --port 8266 -f .pioenvs/prod-ota/firmware.bin

**Comment by nospam2k** [comment]
Ok, I'm still getting the above errors but it seems to be working. I haven't actually pulled the bulbs to check for losing config but I'm getting random results with compiling. I get this error every couple of compiles:

Assembler messages:
 Fatal error: can't create .pioenvs/prod-ota/libbc9/ESP8266WiFi/WiFiClientSecureBearSSL.cpp.o: No such file or directory
 *** [.pioenvs/prod-ota/libbc9/ESP8266WiFi/WiFiClientSecureBearSSL.cpp.o] Error 1
 Assembler messages:
 Fatal error: can't create .pioenvs/prod-ota/src/main.ino.cpp.o: No such file or directory
 *** [.pioenvs/prod-ota/src/main.ino.cpp.o] Error 1
 Assembler messages:

 Fatal error: can't create .pioenvs/prod-ota/libb84/ESPAsyncTCP_ID305/ESPAsyncTCP.cpp.o: No such file or directory
 *** [.pioenvs/prod-ota/libb84/ESPAsyncTCP_ID305/ESPAsyncTCP.cpp.o] Error 1

Also a couple of other random can't create xxxxxxx No such file or directory. When I click compile again, it works. This is on a Mac with Mojave.

**Comment by nospam2k** [comment]
Ok, I'm going to close this because I don't know where the problem lies. It seems that it takes MANY tries to get past errors on compiling and uploading, but if you are persistent and keep clicking the upload, eventually it will work. It took as many as 10 times to get it to work. This is with several different bulbs from two different manufactures.
