### ISSUE TITLE
Add Zemismart Downlights to supported devices

### ISSUE THREAD

**Issue by BestEnemies** [stelgenhof/AiLight#52]
Hi,

Turns out the zemismart downlights here have the same board in them as the AIthinker bulbs. I've had 100% success flashing them with this code.

http://www.zemismart.com/zemismart-au-type-35-inch-wifi-rgbw-led-downlight-10w-voice-control-by-alexa-echo-google-home-assistant-home-automation-ifttt_p0128.html

**Comment by stelgenhof** [comment]
@BestEnemies Thanks a lot! I've added it to the Wiki page.
