### ISSUE TITLE
Gamma setting

### ISSUE THREAD

**Issue by brahmafear** [stelgenhof/AiLight#6]
First, gamma correction is **awesome**.  Loving it.  

On/Off state does not seem to be preserved across device reboots.  Always switches to Off.  

Thanks.

**Comment by stelgenhof** [comment]
Thanks! Do you mean the state of the gamma correction is not preserved?

**Comment by brahmafear** [comment]
Correct.  After firmware flash, gamma switch is off.  Via web interface, I turn gamma on.  Reboot device.  Gamma switch is back to off.  Expected behavior would be for gamma correction switch to be restored to previous state.  

Thanks.

**Comment by stelgenhof** [comment]
Yes, noticed that myself now as well. I'll have a look into that.

**Comment by stelgenhof** [comment]
Fixed it in the latest master branch. Can you check again? Cheers!
