### ISSUE TITLE
Cant use RGB and White LEDs simultaneously in Home Assistant

### ISSUE THREAD

**Issue by hgelpke** [stelgenhof/AiLight#61]
Home Assistant separates the RGB values and white values so you can't dial in actual colors on the color wheel without having to then adjust the white value. Is there a way to eliminate that so it's only one picker?

**Comment by stelgenhof** [comment]
Thanks for the question! 

I haven't used Home Assistant lately to be honest, but to my understanding that's how HomeAssistant works. Perhaps it is possible to ignore the white values settings in HA's setup if you do it manually. But I haven't tried that myself.
