### ISSUE TITLE
Feature Request: Restart via REST API, URL, MQTT

### ISSUE THREAD

**Issue by xbmcnut** [stelgenhof/AiLight#63]
Would love to see and option to restart the bulb other than the webpage as occasionally the bulb goes offline due to network or MQTT server maintenance or power failures. The ability to track online status and restart if non-responsive would be greatly appreciated.

**Comment by stelgenhof** [comment]
@xbmcnut I've been working on this (on and off) in the branch `feature/rest-restart-reload`. Not finished yet, but you can check the progress if you like

Cheers! Sacha

**Comment by xbmcnut** [comment]
Awesome, appreciate the update.
