### ISSUE TITLE
Non MY92xx Driver Support

### ISSUE THREAD

**Issue by erod998** [stelgenhof/AiLight#69]
I have a [led bulb](https://www.amazon.com/dp/B07RZKV7FQ/ref=psdc_2314207011_t3_B07VCRJ9ZM).
I took the bulb apart and see an ESP, but cannot seem to find a LED driver in the bulb. Can the ESP even drive the LEDs directly?  I have attatched a photo of what the board looks like. Any idea if this bulb can work with AiLight? I have been researching but cannot find any info on this bulb. I believe the chip on the left of the ESP is the flash memory. I do not see any LED drivers on the board.
![A031D48C-A053-46AA-9541-2B5C8CEB98C6_1_102_o](https://user-images.githubusercontent.com/31285020/72375962-b2432b80-36d2-11ea-9570-4ebac774074e.jpeg)

**Comment by stelgenhof** [comment]
I don't think the ESP chip can drive the LED's without a driver. The chip on the left looks indeed like a Flash storage. Can you provide more pictures from the bottom side and also the other side?

It seems you can easily connect an FTDI adapter to the PCB (4 pin connector). Many LED bulbs have only test points on the PCB.

Cheers! Sacha
