### ISSUE TITLE
Should "WIFI_OUTPUT_POWER" match your router's TX power?

### ISSUE THREAD

**Issue by donkawechico** [stelgenhof/AiLight#70]
This isn't an issue, but rather a request to add documentation to the wiki for the `WIFI_OUTPUT_POWER` config option -- particularly how to determine the proper value.

For example:
1. In general, should a user set this equal to the transmission power of their router?
2. Are there downsides to setting this value to maximum? (e.g. lessen lifespan of bulb, increased radio interference, etc)
3. Any good resources out there for determining what to set router's TX power to, particularly when you're an IoT enthusiast.

If you like (and if you know the answers), I'm happy to submit a PR adding your insights to the wiki! 

And thank you!

**Comment by stelgenhof** [comment]
Hi @donkawechico 

Not sure if I know all the answers, but this is what I know:

1. No, the WIFI_OUTPUT_POWER is only used for setting the amount of transmission power the module should use. For battery operated devices setting this to the lowest may help in decreasing the energy consumption of the battery
2. Personally I am not aware of any issues with setting this to the highest level. I would suggest to experiment with this value.
3. Same as with point 2, I don't think there is an ideal value as this can differ per person/situation. I would just try with various levels.

A PR is for sure welcome if you have some good information about this topic.

Cheers! Sacha
