### ISSUE TITLE
Implement WS2812FX library of effects

### ISSUE THREAD

**Issue by MatthewCroughan** [stelgenhof/AiLight#71]
https://github.com/kitesurfer1404/WS2812FX

Since the REST API and MQTT is not realtime none of these lovely effects can be implemented by any means right now. WS2812FX provides a really nice set of ideas, is it possible to port such a thing?

**Comment by stelgenhof** [comment]
Thank you @MatthewCroughan for the suggestion. Considering that the AiThinker (and similar lightbulbs) do not have LED's that can be individually addressed, the effects that can be ported are limited. Basically you could only do some blinking and fading of the different RGBW(W) channels.

Another challenge is the limited memory these smart bulbs have. An extensive list of effects wouldn't not be possible to embed in the firmware. It's possible to make this configurable at compile time though, however might still be too large to hold.

Cheers! Sacha
