### ISSUE TITLE
Feature Request: Add config option to set default transition time

### ISSUE THREAD

**Issue by donkawechico** [stelgenhof/AiLight#74]
Would be nice if bulbs could be configured to always transition with some default value set in the config (eventually via UI). Perhaps as "simple" as injecting { ..., `transition: 3`, ... } into each command payload?

For me to do this in Home Assistant, I can't use the wiki's recommended [json schema](https://github.com/stelgenhof/AiLight/wiki/Home-Assistant-Configuration). Instead, I have to use the ["template" schema](https://www.home-assistant.io/integrations/light.mqtt/#template-schema), and manually reconstruct the json payload with the `transition` parameter injected.

**Comment by stelgenhof** [comment]
I think this is possible. Just have to be careful that any additional keys added to the JSON payloads do not interfere with Home Assistant.
